name: RentAnExpert
favicon: null
layout_spectrum: 0.58285
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-36039023-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 0.8205140298232436
purpose: []
