name: RentAnExpert
favicon: null
layout_spectrum: 0.6368
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-36039023-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#afafaf'
    - '#7f7f7f'
    - '#3f3f3f'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
